name: munturai
description: Mobile App Muntur AI, an AI assistance on all car problems and topics
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_image_slideshow: any
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.1
  country_pickers: ^2.0.0
  intl: 0.17.0
  connectivity_plus: ^4.0.1
  image_picker: ^0.8.1
  email_validator: ^2.0.1
  fluttertoast: ^8.0.8
  #wakelock: ^0.5.6
  swipe_to: 1.0.5
  shared_preferences: ^2.0.15
  toggle_switch: ^2.1.0
  http: ^0.13.5
  reflectable: any
  scroll_to_index: ^3.0.1
  #peerdart: ^0.2.0
  #flutter_webrtc: ^0.9.8
  flutter_easyloading: ^3.0.5
  select_form_field: ^2.2.0
  getwidget: ^3.0.1
  #agora_rtc_engine: ^6.1.0
  permission_handler: ^6.1.1
  flutter_local_notifications: ^16.1.0
  open_file: ^3.3.2
  #agora_rtm: ^1.5.0
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.2
  sqflite: ^2.2.8+4
  sqflite_common_ffi_web: any
  #  dio: ^5.4.0
  positioned_scroll_observer: ^2.2.2
  path: ^1.8.2
  url_launcher: ^6.1.11
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  #awesome_notifications: ^0.8.2
  palette_generator: ^0.3.3+3
  scrollable_positioned_list: ^0.3.8
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  webview_flutter: ^4.4.1
  file_picker: ^5.3.1
  package_info_plus: ^4.0.1
  video_player: ^2.7.0
  google_maps_flutter: ^2.2.6
  google_places_autocomplete_text_field: ^0.1.3
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  country_code_picker: ^3.0.0
  calendar_date_picker2: ^0.5.3
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  #qr_flutter: ^4.1.0
  #pdf: ^3.10.1
  #printing: ^5.10.4
  #qr_code_scanner: ^1.0.1
  #qrscan: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_muntur2_200.png"
  web:
    generate: true
    image_path: "assets/images/logo_muntur2_200.png"
    background_color: "#fff"
    theme_color: "#fff"
  windows:
    generate: true
    image_path: "assets/images/logo_muntur2_200.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_muntur2_200.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Aclonica
      fonts:
        - asset: assets/fonts/Aclonica-Regular.ttf
          weight: 400

    - family: Arimo Hebrew Subset
      fonts:
        - asset: assets/fonts/ArimoHebrewSubsetRegular.ttf
          weight: 400
        - asset: assets/fonts/ArimoHebrewSubsetBold.ttf
          weight: 700
    - family: Baloo Bhai
      fonts:
        - asset: assets/fonts/BalooBhaiRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Stream
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/generated/
  line_length: 120
