
import 'package:munturai/model/filter.dart';

final countries_fr=[
  'Afghanistan',
  'Albanie',
  'Antarctique',
  'Algérie',
  'Samoa Américaines',
  'Andorre',
  'Angola',
  'Antigua-et-Barbuda',
  'Azerbaïdjan',
  'Argentine',
  'Australie',
  'Autriche',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Arménie',
  'Barbade',
  'Belgique',
  'Bermudes',
  'Bhoutan',
  'Bolivie',
  'Bosnie-Herzégovine',
  'Botswana',
  'île Bouvet',
  'Brésil',
  'Belize',
  "Territoire Britannique de l'Océan Indien",
  'îles Salomon',
  'îles Vierges Britanniques',
  'Brunéi Darussalam',
  'Bulgarie',
  'Myanmar',
  'Burundi',
  'Bélarus',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cap-vert',
  'îles Caïmanes',
  'République Centrafricaine',
  'Sri Lanka',
  'Tchad',
  'Chili',
  'Chine',
  'Taïwan',
  'île Christmas',
  'îles Cocos (Keeling)',
  'Colombie',
  'Comores',
  'Mayotte',
  'République du Congo',
  'République Démocratique du Congo',
  'îles Cook',
  'Costa Rica',
  'Croatie',
  'Cuba',
  'Chypre',
  'République Tchèque',
  'Bénin',
  'Danemark',
  'Dominique',
  'République Dominicaine',
  'équateur',
  'El Salvador',
  'Guinée équatoriale',
  'éthiopie',
  'érythrée',
  'Estonie',
  'îles Féroé',
  'îles (malvinas) Falkland',
  'Géorgie du Sud et les îles Sandwich du Sud',
  'Fidji',
  'Finlande',
  'îles Âland',
  'France',
  'Guyane Française',
  'Polynésie Française',
  'Terres Australes Françaises',
  'Djibouti',
  'Gabon',
  'Géorgie',
  'Gambie',
  'Territoire Palestinien Occupé',
  'Allemagne',
  'Ghana',
  'Gibraltar',
  'Kiribati',
  'Grèce',
  'Groenland',
  'Grenade',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinée',
  'Guyana',
  'Haïti',
  'îles Heard et Mcdonald',
  'Saint-Siège (état de la Cité du Vatican)',
  'Honduras',
  'Hong-Kong',
  'Hongrie',
  'Islande',
  'Inde',
  'Indonésie',
  "République Islamique d'Iran",
  'Iraq',
  'Irlande',
  'Israel',
  'Italie',
  "Côte d'Ivoire",
  'Jamaïque',
  'Japon',
  'Kazakhstan',
  'Jordanie',
  'Kenya',
  'République Populaire Démocratique de Corée',
  'République de Corée',
  'Koweït',
  'Kirghizistan',
  'République Démocratique Populaire Lao',
  'Liban',
  'Lesotho',
  'Lettonie',
  'Libéria',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaisie',
  'Maldives',
  'Mali',
  'Malte',
  'Martinique',
  'Mauritanie',
  'Maurice',
  'Mexique',
  'Monaco',
  'Mongolie',
  'République de Moldova',
  'Montserrat',
  'Maroc',
  'Mozambique',
  'Oman',
  'Namibie',
  'Nauru',
  'Népal',
  'Pays-Bas',
  'Antilles Néerlandaises',
  'Aruba',
  'Nouvelle-Calédonie',
  'Vanuatu',
  'Nouvelle-Zélande',
  'Nicaragua',
  'Niger',
  'Nigéria',
  'Niué',
  'île Norfolk',
  'Norvège',
  'îles Mariannes du Nord',
  'îles Mineures éloignées des états-Unis',
  'états Fédérés de Micronésie',
  'îles Marshall',
  'Palaos',
  'Pakistan',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pérou',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Portugal',
  'Guinée-Bissau',
  'Timor-Leste',
  'Porto Rico',
  'Qatar',
  'Réunion',
  'Roumanie',
  'Fédération de Russie',
  'Rwanda',
  'Sainte-Hélène',
  'Saint-Kitts-et-Nevis',
  'Anguilla',
  'Sainte-Lucie',
  'Saint-Pierre-et-Miquelon',
  'Saint-Vincent-et-les Grenadines',
  'Saint-Marin',
  'Sao Tomé-et-Principe',
  'Arabie Saoudite',
  'Sénégal',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Viet Nam',
  'Slovénie',
  'Somalie',
  'Afrique du Sud',
  'Zimbabwe',
  'Espagne',
  'Sahara Occidental',
  'Soudan',
  'Suriname',
  'Svalbard etîle Jan Mayen',
  'Swaziland',
  'Suède',
  'Suisse',
  'République Arabe Syrienne',
  'Tadjikistan',
  'Thaïlande',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinité-et-Tobago',
  'émirats Arabes Unis',
  'Tunisie',
  'Turquie',
  'Turkménistan',
  'îles Turks et Caïques',
  'Tuvalu',
  'Ouganda',
  'Ukraine',
  "L'ex-République Yougoslave de Macédoine",
  'égypte',
  'Royaume-Uni',
  'île de Man',
  'République-Unie de Tanzanie',
  'états-Unis',
  'îles Vierges des états-Unis',
  'Burkina Faso',
  'Uruguay',
  'Ouzbékistan',
  'Venezuela',
  'Wallis et Futuna',
  'Samoa',
  'Yémen',
  'Serbie-et-Monténégro',
  'Zambie'];

final countries_eng=[
  'Afghanistan',
  'Albania',
  'Antarctica',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Azerbaijan',
  'Argentina',
  'Australia',
  'Austria',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Armenia',
  'Barbados',
  'Belgium',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'Belize',
  'British Indian Ocean Territory',
  'Solomon Islands',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Myanmar',
  'Burundi',
  'Belarus',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African',
  'Sri Lanka',
  'Chad',
  'Chile',
  'China',
  'Taiwan',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Mayotte',
  'Republic of the Congo',
  'The Democratic Republic Of The Congo',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Benin',
  'Denmark',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'El Salvador',
  'Equatorial Guinea',
  'Ethiopia',
  'Eritrea',
  'Estonia',
  'Faroe Islands',
  'Falkland Islands',
  'South Georgia and the South Sandwich Islands',
  'Fiji',
  'Finland',
  'Âland Islands',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Djibouti',
  'Gabon',
  'Georgia',
  'Gambia',
  'Occupied Palestinian Territory',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Kiribati',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Vatican City State',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Islamic Republic of Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  "CÃ´te d'Ivoire",
  'Jamaica',
  'Japan',
  'Kazakhstan',
  'Jordan',
  'Kenya',
  "Democratic People's Republic of Korea",
  'Republic of Korea',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Lebanon',
  'Lesotho',
  'Latvia',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Monaco',
  'Mongolia',
  'Republic of Moldova',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Oman',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'Aruba',
  'New Caledonia',
  'Vanuatu',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Norway',
  'Northern Mariana Islands',
  'United States Minor Outlying Islands',
  'Federated States of Micronesia',
  'Marshall Islands',
  'Palau',
  'Pakistan',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Guinea-Bissau',
  'Timor-Leste',
  'Puerto Rico',
  'Qatar',
  'Réunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Anguilla',
  'Saint Lucia',
  'Saint-Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Vietnam',
  'Slovenia',
  'Somalia',
  'South Africa',
  'Zimbabwe',
  'Spain',
  'Western Sahara',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'United Arab Emirates',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'The Former Yugoslav Republic of Macedonia',
  'Egypt',
  'United Kingdom',
  'Isle of Man',
  'United Republic Of Tanzania',
  'United States',
  'U.S. Virgin Islands',
  'Burkina Faso',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Wallis and Futuna',
  'Samoa',
  'Yemen',
  'Serbia and Montenegro',
  'Zambia'];

final regions=[
  'ADAMOUA',
  'CENTRE',
  'EST',
  'EXTREME NORD',
  'LITTORAL',
  'NORD',
  'NORD OUEST',
  'OUEST',
  'SUD' ,
  'SUD OUEST'
];

final departements = [
  {'MOUNGO': {'region': 'LITTORAL'}},
  {'KADEY': {'region': 'EST'}},
  {'HAUTS PLATEAUX': {'region': 'OUEST'}},
  {'NDE': {'region': 'OUEST'}},
  {'LOGONE ET CHARI': {'region': 'EXTREME NORD'}},
  {'LOM ET DJEREM': {'region': 'EST'}},
  {'BOYO': {'region': 'NORD OUEST'}},
  {'MEZAM': {'region': 'NORD OUEST'}},
  {'MAYO-BANYO': {'region': 'ADAMOUA'}},
  {'MENCHUNG': {'region': 'NORD OUEST'}},
  {'MAYO SAVA': {'region': 'EXTREME NORD'}},
  {'NGO-KETUNJIA': {'region': 'NORD OUEST'}},
  {'NOUN': {'region': 'OUEST'}},
  {'MBAM ET INOUBOU': {'region': 'CENTRE'}},
  {'SANAGA MARITIME': {'region': 'LITTORAL'}},
  {'MEFOU ET AKONO': {'region': 'CENTRE'}},
  {'BOUMBA ET NGOKO': {'region': 'EST'}},
  {'MANYU': {'region': 'SUD OUEST'}},
  {'KOUPE MANENGOUMBA': {'region': 'SUD OUEST'}},
  {'WOURI': {'region': 'LITTORAL'}},
  {'MAYO REY': {'region': 'NORD'}},
  {'MVILA': {'region': 'SUD'}},
  {'BENOUE': {'region': 'NORD'}},
  {'BUI': {'region': 'NORD OUEST'}},
  {'HAUT NKAM': {'region': 'OUEST'}},
  {'MIFI': {'region': 'OUEST'}},
  {'MEME': {'region': 'SUD OUEST'}},
  {'NYONG ET MFOUMOU': {'region': 'CENTRE'}},
  {'LEBIALEM': {'region': 'SUD OUEST'}},
  {'FARO': {'region': 'NORD'}},
  {'NYONG ET KELLE': {'region': 'CENTRE'}},
  {'MAYO KANI': {'region': 'EXTREME NORD'}},
  {'MFOUNDI': {'region': 'CENTRE'}},
  {'MAYO DANAY': {'region': 'EXTREME NORD'}},
  {'MAYO TSANAGA': {'region': 'EXTREME NORD'}},
  {'DONGA MANTUNG': {'region': 'NORD OUEST'}},
  {'NYONG ET SOO': {'region': 'CENTRE'}},
  {'OCEAN': {'region': 'SUD'}},
  {'DJA ET LOBO': {'region': 'SUD'}},
  {'NKAM': {'region': 'LITTORAL'}},
  {'KOUNG KHI': {'region': 'OUEST'}},
  {'MBERE': {'region': 'ADAMOUA'}},
  {'MAYO LOUTI': {'region': 'NORD'}},
  {'MENOUA': {'region': 'OUEST'}},
  {'MEFOU ET AFAMBA': {'region': 'CENTRE'}},
  {'FARO ET DEO': {'region': 'ADAMOUA'}},
  {'MBAM ET KIM': {'region': 'CENTRE'}},
  {'MOMO': {'region': 'NORD OUEST'}},
  {'NDJEREM': {'region': 'ADAMOUA'}},
  {'DIAMARE': {'region': 'EXTREME NORD'}},
  {'FAKO': {'region': 'SUD OUEST'}},
  {'BAMBOUTOS': {'region': 'OUEST'}},
  {'LEKIE': {'region': 'CENTRE'}},
  {'HAUTE SANAGA': {'region': 'CENTRE'}},
  {'HAUT NYONG': {'region': 'EST'}},
  {'NDIAN': {'region': 'SUD OUEST'}},
  {'VALLE DU NTEM': {'region': 'SUD'}}
];

final communes=[{'BALI-KUMBAT': {'region': 'NORD OUEST', 'departement': 'NGO-KETUNJIA'}},
  {'NSEM': {'region': 'CENTRE', 'departement': 'HAUTE SANAGA'}},
  {'NKOLAFAMBA': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'KOUSSERI': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'MENGUEME': {'region': 'CENTRE', 'departement': 'NYONG ET SOO'}},
  {'MOUDEMBA': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'NDELELE': {'region': 'EST', 'departement': 'KADEY'}},
  {'FONFUKA': {'region': 'NORD OUEST', 'departement': 'BOYO'}},
  {'MELONG': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'DZIGUILAO': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'WOURI 2': {'region': 'LITTORAL', 'departement': 'WOURI'}},
  {'BAFIA': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'LIMBE 1': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'NWA': {'region': 'NORD OUEST', 'departement': 'DONGA MANTUNG'}},
  {'MAGBA': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'KENTZOU': {'region': 'EST', 'departement': 'KADEY'}},
  {'FONGO TONGO': {'region': 'OUEST', 'departement': 'MENOUA'}},
  {'ELAK': {'region': 'NORD OUEST', 'departement': 'BUI'}},
  {'TOUROUA': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'OMBESSA': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'GUIDIGUIS': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'FIGUIL': {'region': 'NORD', 'departement': 'MAYO LOUTI'}},
  {'DARGALA': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'TIBATI': {'region': 'ADAMOUA', 'departement': 'FARO ET DEO'}},
  {'TOKO': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'MANJO': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'MBANDJOCK': {'region': 'CENTRE', 'departement': 'HAUTE SANAGA'}},
  {'DIBANG': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'BOT MAKAK': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'KAELE': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'BIYOUHA': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'WAZA': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'BOURHA': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'WOURI 3': {'region': 'LITTORAL', 'departement': 'WOURI'}},
  {'BERTOUA 2': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'BIAME': {'region': 'NORD OUEST', 'departement': 'BUI'}},
  {'MAKENENE': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'EKONDO TITI': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'MOULOUNDOU': {'region': 'EST', 'departement': 'BOUMBA ET NGOKO'}},
  {'MFOUNDI 3': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'WIDIKUM-BOFFE': {'region': 'NORD OUEST', 'departement': 'MOMO'}},
  {'NGONG': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'BELO': {'region': 'NORD OUEST', 'departement': 'BOYO'}},
  {'SAA': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'YAGOUA': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'LOBO': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'MFOU': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'NGULEBOCK': {'region': 'EST', 'departement': 'KADEY'}},
  {'MISAJE': {'region': 'NORD OUEST', 'departement': 'DONGA MANTUNG'}},
  {"MA'AN": {'region': 'SUD', 'departement': 'VALLE DU NTEM'}},
  {'KOMBO ITINDI': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'MAKARI': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'LOLODORF': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'BANKA': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'BATIBO': {'region': 'NORD OUEST', 'departement': 'MOMO'}},
  {'NANGA EBOKO': {'region': 'CENTRE', 'departement': 'HAUTE SANAGA'}},
  {'MOZOGO': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'MORA': {'region': 'EXTREME NORD', 'departement': 'MAYO SAVA'}},
  {'SANTA': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'MESSOCK': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'BANDJA': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'IDABATO': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'MADINGRING': {'region': 'NORD', 'departement': 'MAYO REY'}},
  {'LOMIE': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'DIBAMBA': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'NGUELEMENDOUGA': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'KONYE': {'region': 'SUD OUEST', 'departement': 'MEME'}},
  {'LOUM': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'LOUKOUNDJE': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'NDU': {'region': 'NORD OUEST', 'departement': 'DONGA MANTUNG'}},
  {'MINTOM': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'DIMAKO': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'MEYOMESSI': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'MBANKOMO': {'region': 'CENTRE', 'departement': 'MEFOU ET AKONO'}},
  {'KEKEM': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'MAROUA 2': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'NGUTI': {'region': 'SUD OUEST', 'departement': 'KOUPE MANENGOUMBA'}},
  {'NGOMEDZAP': {'region': 'CENTRE', 'departement': 'NYONG ET SOO'}},
  {'MBONGUE': {'region': 'SUD OUEST', 'departement': 'MEME'}},
  {'KOUTABA': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'BUEA': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'NSANGMELIMA': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'NJOMBE PENJA': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'KOUOPTAMO': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'LIMBE 3': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'WOURI 4': {'region': 'LITTORAL', 'departement': 'WOURI'}},
  {'BATCHENGA': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'OULI': {'region': 'EST', 'departement': 'KADEY'}},
  {'NGORO': {'region': 'CENTRE', 'departement': 'MBAM ET KIM'}},
  {'WOURI 6': {'region': 'LITTORAL', 'departement': 'WOURI'}},
  {'AKOEMAN': {'region': 'CENTRE', 'departement': 'NYONG ET SOO'}},
  {'ATOK': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'EDEA 1': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'NDOUKOULA': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'BONALEA': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'BANA': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'MAROUA 1': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'NJIKWA': {'region': 'NORD OUEST', 'departement': 'MOMO'}},
  {'YINGUI': {'region': 'LITTORAL', 'departement': 'NKAM'}},
  {'KOBDOMBO': {'region': 'CENTRE', 'departement': 'NYONG ET MFOUMOU'}},
  {'DARACK': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'MONATELE': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'JAKIRI': {'region': 'NORD OUEST', 'departement': 'BUI'}},
  {'MVENGUE': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'BANGOURAIN': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'IDENAU': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'DZENG': {'region': 'CENTRE', 'departement': 'NYONG ET SOO'}},
  {'TIKO': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'LIMBE 2': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'TCHOLIRRE': {'region': 'NORD', 'departement': 'MAYO REY'}},
  {'GUIDER': {'region': 'NORD', 'departement': 'MAYO LOUTI'}},
  {'MOMBO': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'GAROUA 1': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'MFOUNDI 7': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'BATCHAM': {'region': 'OUEST', 'departement': 'BAMBOUTOS'}},
  {'BETARE OYA': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'NJIMON': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'KON YAMBETTA': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'NKONGSAMBA 1': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'NKUM': {'region': 'NORD OUEST', 'departement': 'BUI'}},
  {'KAI KAI': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'MEYOMESSALA': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'ANDEK': {'region': 'NORD OUEST', 'departement': 'MOMO'}},
  {'EBEBDA': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'NTUI': {'region': 'CENTRE', 'departement': 'MBAM ET KIM'}},
  {'TOBOURO': {'region': 'NORD', 'departement': 'MAYO LOUTI'}},
  {'AKWAYA': {'region': 'SUD OUEST', 'departement': 'MANYU'}},
  {'AWAE': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'BANWA': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'WOURI 1': {'region': 'LITTORAL', 'departement': 'WOURI'}},
  {'KAR HAY': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'AYOS': {'region': 'CENTRE', 'departement': 'NYONG ET MFOUMOU'}},
  {'MINDIF': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'BARE BAKEM': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'CAMPO': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'SALAPOUMBE': {'region': 'EST', 'departement': 'BOUMBA ET NGOKO'}},
  {'GUEME VELE': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'NDIKINIMEKI': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'BANGEM': {'region': 'SUD OUEST', 'departement': 'KOUPE MANENGOUMBA'}},
  {'NKAMBE': {'region': 'NORD OUEST', 'departement': 'DONGA MANTUNG'}},
  {'MBENGWI': {'region': 'NORD OUEST', 'departement': 'MOMO'}},
  {'TOULOUM': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'ALOU': {'region': 'SUD OUEST', 'departement': 'LEBIALEM'}},
  {'KOLOFATA': {'region': 'EXTREME NORD', 'departement': 'MAYO SAVA'}},
  {'GAROUA BOULAI\x8f': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'NKONDJOCK': {'region': 'LITTORAL', 'departement': 'NKAM'}},
  {'BAFANG': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'HILE ALIFA': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'DIR': {'region': 'ADAMOUA', 'departement': 'MBERE'}},
  {'MBANGA': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'PITOA': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'OLANGUINA': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'GAZAWA': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'GUERE': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'ZINA': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'MENJI': {'region': 'SUD OUEST', 'departement': 'LEBIALEM'}},
  {'FIGUL': {'region': 'NORD', 'departement': 'FARO'}},
  {'NGAMBE TIKAR': {'region': 'CENTRE', 'departement': 'MBAM ET KIM'}},
  {'MOULVOUDAYE': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'NKOLMETET': {'region': 'CENTRE', 'departement': 'NYONG ET SOO'}},
  {'EYUMOJOCK': {'region': 'SUD OUEST', 'departement': 'MANYU'}},
  {'DOUME': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'BAFUT': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'BAZOU': {'region': 'OUEST', 'departement': 'MIFI'}},
  {'BAMENDA 3': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'BAMENDJOU': {'region': 'OUEST', 'departement': 'HAUTS PLATEAUX'}},
  {'DIZANGUE': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'SOMALOMO': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'Djohong': {'region': 'ADAMOUA', 'departement': 'MBERE'}},
  {'OLAMZE': {'region': 'SUD', 'departement': 'VALLE DU NTEM'}},
  {'KETTE': {'region': 'EST', 'departement': 'KADEY'}},
  {'BELABO': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'AKOM 2': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'ABONG MBANG': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'NGAMBE': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'PENKA MICHEL': {'region': 'OUEST', 'departement': 'MENOUA'}},
  {'BONDJOCK': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'AKO': {'region': 'NORD OUEST', 'departement': 'DONGA MANTUNG'}},
  {'GAROUA 2': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'NDJOUM': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'REY BOUBA': {'region': 'NORD', 'departement': 'MAYO REY'}},
  {'BENGBIS': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'NDOBIAN': {'region': 'LITTORAL', 'departement': 'NKAM'}},
  {'TOMBEL': {'region': 'SUD OUEST', 'departement': 'KOUPE MANENGOUMBA'}},
  {'MENGANG': {'region': 'CENTRE', 'departement': 'NYONG ET MFOUMOU'}},
  {'MAYO HOURNA': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'BOGO': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'BLANGOUA': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'FOUMBOT': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'KONG NI': {'region': 'OUEST', 'departement': 'MENOUA'}},
  {'KRIBI 2': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'BENAKUMA': {'region': 'NORD OUEST', 'departement': 'MENCHUNG'}},
  {'BASSAMBA': {'region': 'OUEST', 'departement': 'NDE'}},
  {'SOULEDE ROUA': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'BANGOU': {'region': 'OUEST', 'departement': 'HAUTS PLATEAUX'}},
  {'NDOP': {'region': 'NORD OUEST', 'departement': 'NGO-KETUNJIA'}},
  {'HINA': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'KALFOU': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'LAGDO': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'AFANLOUM': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'MAYO BALEO': {'region': 'ADAMOUA', 'departement': 'FARO ET DEO'}},
  {'NGOG MAPUBI': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'BIBEMI': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'EBONE': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'BANYO': {'region': 'ADAMOUA', 'departement': 'MAYO-BANYO'}},
  {'AKONOLINGA': {'region': 'CENTRE', 'departement': 'NYONG ET MFOUMOU'}},
  {'BATOURI': {'region': 'EST', 'departement': 'KADEY'}},
  {'BAKOU': {'region': 'OUEST', 'departement': 'HAUT NKAM'}},
  {'BERTOUA 1': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'GOULFEY': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'LEMBE YEZOUM': {'region': 'CENTRE', 'departement': 'HAUTE SANAGA'}},
  {'MINTA': {'region': 'CENTRE', 'departement': 'HAUTE SANAGA'}},
  {'WINA': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'EDZEDZOUAN': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'ZHOA': {'region': 'NORD OUEST', 'departement': 'MENCHUNG'}},
  {'EBOLOWA 2': {'region': 'SUD', 'departement': 'MVILA'}},
  {'MENGONG': {'region': 'SUD', 'departement': 'MVILA'}},
  {'EBOLOWA 1': {'region': 'SUD', 'departement': 'MVILA'}},
  {'MANDJOU': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'WOURI 5': {'region': 'LITTORAL', 'departement': 'WOURI'}},
  {'LOGONE BIRNI': {'region': 'EXTREME NORD',
    'departement': 'LOGONE ET CHARI'}},
  {'MANFE': {'region': 'SUD OUEST', 'departement': 'MANYU'}},
  {'NGUIBASSAL': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'NITOUKOU': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'MOKOLO': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'BAMUSSO': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'BIWONG BANE': {'region': 'SUD', 'departement': 'MVILA'}},
  {'BAMENDA 2': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'NGOURA': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'KYE OSSI': {'region': 'SUD', 'departement': 'VALLE DU NTEM'}},
  {'MASSOCK SONG LOULOU': {'region': 'LITTORAL',
    'departement': 'SANAGA MARITIME'}},
  {'YOKADOUMA': {'region': 'EST', 'departement': 'BOUMBA ET NGOKO'}},
  {'BAFOUSSAM 2': {'region': 'OUEST', 'departement': 'MIFI'}},
  {'DEMBO': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'MBOUDA': {'region': 'OUEST', 'departement': 'BAMBOUTOS'}},
  {'MAROUA 3': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'NKONGSAMBA 2': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'BANKIM': {'region': 'ADAMOUA', 'departement': 'MAYO-BANYO'}},
  {'MOGODE': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'MINDOUROU': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'EVODOULA': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'BAYANGAM': {'region': 'OUEST', 'departement': 'KOUNG KHI'}},
  {'BIPINDI': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'ANGOSSAS': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'TINTO': {'region': 'SUD OUEST', 'departement': 'MANYU'}},
  {'BANSCHEO': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'MFOUNDI 4': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'NGOULEMAKONG': {'region': 'SUD', 'departement': 'MVILA'}},
  {'KUMBA 1': {'region': 'SUD OUEST', 'departement': 'MEME'}},
  {'ESEKA': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'ISANGUELE': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'FUNDONG': {'region': 'NORD OUEST', 'departement': 'BOYO'}},
  {'KUMBA 3': {'region': 'SUD OUEST', 'departement': 'MEME'}},
  {'AKONO': {'region': 'CENTRE', 'departement': 'MEFOU ET AKONO'}},
  {'BAHAM': {'region': 'OUEST', 'departement': 'HAUTS PLATEAUX'}},
  {'MOUTOURWA': {'region': 'EXTREME NORD', 'departement': 'MAYO KANI'}},
  {'WUM': {'region': 'NORD OUEST', 'departement': 'MENCHUNG'}},
  {'MAKAK': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'BAFOUSSAM 1': {'region': 'OUEST', 'departement': 'MIFI'}},
  {'SANTCHOU': {'region': 'OUEST', 'departement': 'MENOUA'}},
  {'MOUANKO': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'MFOUNDI 1': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'KUMBA 2': {'region': 'SUD OUEST', 'departement': 'MEME'}},
  {'POUMA': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'TIGNERE': {'region': 'ADAMOUA', 'departement': 'FARO ET DEO'}},
  {'PETTE': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'KOMBO ABEDIMO': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'NKONGSAMBA 3': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'DEMDING': {'region': 'OUEST', 'departement': 'KOUNG KHI'}},
  {'ZOETELE': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'DATCHEKA': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'FOKOUE': {'region': 'OUEST', 'departement': 'MENOUA'}},
  {'BAMENDA 1': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'KUMBO': {'region': 'NORD OUEST', 'departement': 'BUI'}},
  {'MESSAMENA': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'DIBOMBARI': {'region': 'LITTORAL', 'departement': 'MOUNGO'}},
  {'ESSE': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'MAGA': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'BIWONG BULU': {'region': 'SUD', 'departement': 'MVILA'}},
  {'AMBAM': {'region': 'SUD', 'departement': 'VALLE DU NTEM'}},
  {'KIIKI': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'NGOUMOU': {'region': 'CENTRE', 'departement': 'MEFOU ET AKONO'}},
  {'OKOLA': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'MBALMAYO': {'region': 'CENTRE', 'departement': 'NYONG ET SOO'}},
  {'KRIBI 1': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'MFOUNDI 2': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'GAOUI': {'region': 'ADAMOUA', 'departement': 'MBERE'}},
  {'MBOMA': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'NYANON': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'MESSONDO': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'GARI GOMBO': {'region': 'EST', 'departement': 'BOUMBA ET NGOKO'}},
  {'NGAOUNDAL': {'region': 'ADAMOUA', 'departement': 'NDJEREM'}},
  {'TOKOBERE': {'region': 'EXTREME NORD', 'departement': 'MAYO SAVA'}},
  {'MUYUKA': {'region': 'SUD OUEST', 'departement': 'FAKO'}},
  {'MFOUNDI 5': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'GAROUA 3': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'NGWEI': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'MATOMB': {'region': 'CENTRE', 'departement': 'NYONG ET KELLE'}},
  {'NKOR': {'region': 'NORD OUEST', 'departement': 'BUI'}},
  {'DSCHANG': {'region': 'OUEST', 'departement': 'MENOUA'}},
  {'DOUMAINTANG': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'YOKO': {'region': 'CENTRE', 'departement': 'MBAM ET KIM'}},
  {'FOUMBAN': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'DEUK': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'MALANTOUEN': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'MVANGAN': {'region': 'SUD', 'departement': 'MVILA'}},
  {'SOA': {'region': 'CENTRE', 'departement': 'MEFOU ET AFAMBA'}},
  {'BALI': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'BATIE': {'region': 'OUEST', 'departement': 'HAUTS PLATEAUX'}},
  {'GALIM': {'region': 'OUEST', 'departement': 'BAMBOUTOS'}},
  {'BEBEY': {'region': 'CENTRE', 'departement': 'HAUTE SANAGA'}},
  {'PETE BANDJOUN': {'region': 'OUEST', 'departement': 'KOUNG KHI'}},
  {'KONCHA': {'region': 'ADAMOUA', 'departement': 'FARO ET DEO'}},
  {'KOZA': {'region': 'EXTREME NORD', 'departement': 'MAYO TSANAGA'}},
  {'EFOULAN': {'region': 'SUD', 'departement': 'MVILA'}},
  {'MAYO OULO': {'region': 'NORD', 'departement': 'MAYO LOUTI'}},
  {'FURU AWA': {'region': 'NORD OUEST', 'departement': 'MENCHUNG'}},
  {'TONGA': {'region': 'OUEST', 'departement': 'NDE'}},
  {'TUBAH': {'region': 'NORD OUEST', 'departement': 'MEZAM'}},
  {'DIANG': {'region': 'EST', 'departement': 'LOM ET DJEREM'}},
  {'MEIGANGA': {'region': 'ADAMOUA', 'departement': 'MBERE'}},
  {'NIETE': {'region': 'SUD', 'departement': 'OCEAN'}},
  {'BANGANGTE': {'region': 'OUEST', 'departement': 'NDE'}},
  {'YABASSI': {'region': 'LITTORAL', 'departement': 'NKAM'}},
  {'MBANGASSINA': {'region': 'CENTRE', 'departement': 'MBAM ET KIM'}},
  {'FOTOKOL': {'region': 'EXTREME NORD', 'departement': 'LOGONE ET CHARI'}},
  {'OBALA': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'MFOUNDI 6': {'region': 'CENTRE', 'departement': 'MFOUNDI'}},
  {'BABESSI': {'region': 'NORD OUEST', 'departement': 'NGO-KETUNJIA'}},
  {'GOYLA': {'region': 'EST', 'departement': 'HAUT NYONG'}},
  {'BOKITO': {'region': 'CENTRE', 'departement': 'MBAM ET INOUBOU'}},
  {'ENDOM': {'region': 'CENTRE', 'departement': 'NYONG ET MFOUMOU'}},
  {'NDOM': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'EDEA 2': {'region': 'LITTORAL', 'departement': 'SANAGA MARITIME'}},
  {'MASSANGAM': {'region': 'OUEST', 'departement': 'NOUN'}},
  {'GOBO': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}},
  {'DIKOME BALUE': {'region': 'SUD OUEST', 'departement': 'NDIAN'}},
  {'MAYO DARLE': {'region': 'ADAMOUA', 'departement': 'MAYO-BANYO'}},
  {'BEKA': {'region': 'NORD', 'departement': 'FARO'}},
  {'GASCHIGA': {'region': 'NORD', 'departement': 'BENOUE'}},
  {'WAMBANE': {'region': 'SUD OUEST', 'departement': 'LEBIALEM'}},
  {'MERI': {'region': 'EXTREME NORD', 'departement': 'DIAMARE'}},
  {'BAFOUSSAM 3': {'region': 'OUEST', 'departement': 'MIFI'}},
  {'NJINIKOM': {'region': 'NORD OUEST', 'departement': 'BOYO'}},
  {'OVENG': {'region': 'SUD', 'departement': 'DJA ET LOBO'}},
  {'BABADJOU': {'region': 'OUEST', 'departement': 'BAMBOUTOS'}},
  {'ELIG-MFOMO': {'region': 'CENTRE', 'departement': 'LEKIE'}},
  {'BIKOK': {'region': 'CENTRE', 'departement': 'MEFOU ET AKONO'}},
  {'MBANG': {'region': 'EST', 'departement': 'KADEY'}},
  {'TCHATIBALI': {'region': 'EXTREME NORD', 'departement': 'MAYO DANAY'}}];

final List<String> postes = [
  "SG",
  "SGN",
  "DEP",
  "DER",
  "DED",
  "DEC",
  "DECON",
  "DEPAYS",
  "Point Focal Region",
  "SG DEP",
  "Delegue Regional",
  "SG CA",
  "Resp. Comm + Pub",
  "Agent Comm",
  "Resp. Lobbying",
  "SG1 DEP",
  "SG2 DEP",
  "SG3 DEP",
  "Volontaire",
  "Mandataire ELECAM",
  "Militant",
  "Citoyen"
];

final List<String> graduators = [
  "Admin",
  "PN",
  "SGN",
  "DEP",
];

bool isGraduator(String elt){
  for(var i=0;i<graduators.length;i++)
    if(elt.toLowerCase().contains(graduators[i].toLowerCase()))
      return true;
  return false;
}

searchType Zone(String poste){
  var postesDED=['DED'];
  var postesDER=['DER',
    "Point Focal Region",
    "Delegue Regional"
  ];
  var postesDEPays=[
    "DECON",
    "DEPAYS",];
  for(var i=0;i<postesDED.length;i++)
    if(poste.toLowerCase()==postesDED[i].toLowerCase())
      return searchType.department;
  for(var i=0;i<postesDER.length;i++)
    if(poste.toLowerCase()==postesDER[i].toLowerCase())
      return searchType.region;
  for(var i=0;i<postesDEPays.length;i++)
    if(poste.toLowerCase()==postesDEPays[i].toLowerCase())
      return searchType.pays;

  return searchType.commune;
}

List<String> depsFromReg(String region){
  List<String> res=[];
  for(var i = 0;i<departements.length;i++){
    var key=departements[i].keys.firstWhere((element) => element != '',orElse: () => 'None');
    if((departements[i][key] as Map)['region'] == region)
      res.add(key);
  }
  return res;
}

List<String> alldeps(){
  List<String> res=[];
  for(var i = 0;i<departements.length;i++){
      res.add(departements[i].keys.firstWhere((element) => element != '',orElse: () => 'None'));
  }
  return res;
}

List<String> comsFromReg(String region){
  List<String> res=[];
  for(var i = 0;i<communes.length;i++){
    var key = communes[i].keys.firstWhere((element) => element != '',orElse: () => 'None');
    if((communes[i][key] as Map)['region'] == region)
      res.add(key);
  }
  return res;
}

List<String> comsFromDep(String departement){
  List<String> res=[];
  for(var i = 0;i<communes.length;i++){
    var key = communes[i].keys.firstWhere((element) => element != '',orElse: () => 'None');
    if((communes[i][key] as Map)['departement'] == departement)
      res.add(key);
  }
  return res;
}

String depFrmunturom(String commune){
  for(var i = 0;i<communes.length;i++){
    var key = communes[i].keys.firstWhere((element) => element != '',orElse: () => 'None');
    if(key==commune)
      return (communes[i][key] as Map)['departement'];
  }
  return "";
}

String regFrmunturom(String commune){
  for(var i = 0;i<communes.length;i++){
    var key = communes[i].keys.firstWhere((element) => element != '',orElse: () => 'None');
    if(key==commune)
      return (communes[i][key] as Map)['region'];
  }
  return "";
}

String regFromDep(String departement){
  for(var i = 0;i<departements.length;i++){
    var key = departements[i].keys.firstWhere((element) => element != '',orElse: () => 'None');
    if(key==departement)
      return (departements[i][key] as Map)['region'];
  }
  return "";
}


